ecr_repo               = "webshop-api-auth-svc"
bucket_name            = "webshop-api-auth-svc"
codebuild_project_name = "WebshopAPI-AuthMS"
repo_owner             = "Baja-KS"
repo                   = "WebshopAPI-AuthenticationService"
branch                 = "main"
pipeline_name          = "auth-svc-ci-cd"